### ISSUE TITLE
IAM URL mismatch

### ISSUE THREAD

**Issue by AstraLuma** [tigrisdata/tigris-os-docs#137]
https://www.tigrisdata.com/docs/api/s3/ says the IAM endpoint is `https://fly.storage.tigris.dev:8009`

https://www.tigrisdata.com/docs/sdks/s3/aws-cli/ says the IAM endpoint is `https://fly.iam.storage.tigris.dev`

**Comment by JigarJoshi** [comment]
Hello @AstraLuma - Thanks for reporting this mismatch. https://github.com/tigrisdata/tigris-os-docs/pull/138
